name: Publish

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: |
        rm -rf .git/
        git clone --depth=1 --single-branch --branch gh-pages https://${{ secrets.GH_PAT }}@github.com/coretechonomy/docs.git gh-pages

        if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
        elif [ -e package-lock.json ]; then
          npm ci
        else
          npm i
        fi

        yarn build
        rsync -a build/ gh-pages/

        cd gh-pages/
        echo "docs.coretechonomy.com" > CNAME

        git config --global user.name "Erik Thomsen"
        git config --global user.email "ethomsen86@gmail.com"

        git add -A
        git commit -m "Deploy website - based on $GITHUB_SHA"
        git push