name: Publish

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }} # Required due to: https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: |
        git clone --depth=1 --single-branch --branch gh-pages https://git@github.com/coretechonomy/docs.git gh-pages
        rm -rf .git/

        if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
        elif [ -e package-lock.json ]; then
          npm ci
        else
          npm i
        fi

        yarn build
        which rsync
        rsync -a build/ gh-pages/
        cd gh-pages/
        echo "docs.coretechonomy.com" > CNAME

        git config --global user.name "Erik Thomsen"
        git config --global user.email "ethomsen86@gmail.com"

        git add -A
        git commit -m "Deploy website - based on $GITHUB_SHA"
        git push -f