name: Publish

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Build and deploy website
      run: |
        if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
        elif [ -e package-lock.json ]; then
          npm ci
        else
          npm i
        fi

        yarn build && cd build/
        
        echo "docs.coretechonomy.com" > CNAME

        git init
        git config --global user.name "Erik Thomsen"
        git config --global user.email "ethomsen86@gmail.com"

        git remote add origin https://${{ secrets.GH_PAT }}@github.com/coretechonomy/docs.git
        git checkout -b gh-pages
        git add -A
        git commit -m "Deploy website - based on $GITHUB_SHA"
        git push -f origin gh-pages